[general]
WebsocketPort = 8765

[general.github]
Token = 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

[node]
LoggerVersion = latest
ESP32VidPid = 10c4:ea60