[general]
WebsocketPort = 8765
APIPort = 8000

[general.github]
Token = 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

[node]
ESP32VidPid = 10c4:ea60
PrintLogs = False